Add a way to Scan a QR Code that contain a Gziped JSON
idpass/smartscanner-core pull request #37
Opened 2021-01-22 07:56 UTC by rjmangubat23

### Issue

#21 Add a way to Scan a QR Code that contain a Gziped JSON 

### Changes

- Add Scan a QR Code containing Gzipped JSON implementation 
- Add Gzipped JsonPath dependencies
- Refactor and code clean up of library and app core classes
- Update smartscanner-android api via https://github.com/idpass/smartscanner-android/pull/3

2021-01-22 13:52 UTC, jeremi requested changes

2021-01-22 13:52 UTC, jeremi commented on core-lib/src/main/java/org/idpass/smartscanner/lib/barcode/BarcodeAnalyzer.kt
> +    private fun sendGzippedResult(rawValue : String, rawBytes: ByteArray) {
It is not always gzipped, can you rename to `sendQrCodeResult` maybe?

2021-01-22 13:52 UTC, jeremi commented on core-lib/src/main/java/org/idpass/smartscanner/lib/barcode/BarcodeAnalyzer.kt
> +            jsonPath?.let { path ->
What if the json is not gzipped? JSON will not always be gzipped

2021-01-22 13:52 UTC, jeremi commented on core-lib/src/main/AndroidManifest.xml
> +                <action android:name="org.idpass.smartscanner.QRCODE_SCAN" />
we need `org.idpass.smartscanner.QRCODE_SCAN` and `org.idpass.smartscanner.odk.QRCODE_SCAN` for consistency

2021-01-22 13:52 UTC, jeremi commented on core-lib/src/main/java/org/idpass/smartscanner/lib/barcode/BarcodeAnalyzer.kt
> +        val isGzipped = intent.getBooleanExtra(ScannerConstants.GZIPPED_ENABLED, true)
default to false

2021-01-22 13:52 UTC, jeremi commented on core-lib/src/main/java/org/idpass/smartscanner/lib/barcode/BarcodeAnalyzer.kt
> +        val isJson = intent.getBooleanExtra(ScannerConstants.JSON_ENABLED, true)
default to false

2021-01-25 08:11 UTC, rjmangubat23 commented
@jeremi requested changes are now resolved in latest commit. May I ask for re-review and approval so that I can be able to merge? Thank you!

2021-01-27 03:05 UTC, merged